/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import {
  FaHeartPulse,
  FaCircleExclamation,
  FaTriangleExclamation,
  FaBoxArchive,
  FaCircleArrowDown,
  FaArrowDown,
  FaArrowRight,
  FaRightLeft,
  FaCircleArrowUp,
  FaArrowUp,
  FaCircleCheck,
  FaChartBar,
  FaChartSimple,
  FaBell,
  FaBox,
  FaBoxesStacked,
  FaTrowelBricks,
  FaBuilding,
  FaCalculator,
  FaCalendarDays,
  FaCalendarCheck,
  FaCamera,
  FaCheck,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaClipboard,
  FaClipboardCheck,
  FaClock,
  FaCoins,
  FaCompass,
  FaMicrochip,
  FaCreditCard,
  FaDollarSign,
  FaDownload,
  FaPen,
  FaPenToSquare,
  FaArrowUpRightFromSquare,
  FaEye,
  FaIndustry,
  FaFileCircleCheck,
  FaFileCode,
  FaFileArrowDown,
  FaFileLines,
  FaFileExcel,
  FaFilter,
  FaSeedling,
  FaFolderTree,
  FaGlobe,
  FaHandHoldingDollar,
  FaHandshake,
  FaHardDrive,
  FaHelmetSafety,
  FaCircleQuestion,
  FaClockRotateLeft,
  FaImage,
  FaKey,
  FaLandmark,
  FaLayerGroup,
  FaGauge,
  FaBorderAll,
  FaSpinner,
  FaLock,
  FaRightFromBracket,
  FaEnvelope,
  FaMapPin,
  FaPercent,
  FaPhone,
  FaChartPie,
  FaPlay,
  FaPlus,
  FaPrint,
  FaQrcode,
  FaReceipt,
  FaArrowsRotate,
  FaRotateLeft,
  FaFloppyDisk,
  FaExpand,
  FaMagnifyingGlass,
  FaPaperPlane,
  FaGear,
  FaShield,
  FaShieldHalved,
  FaBagShopping,
  FaCartShopping,
  FaWandSparkles,
  FaTag,
  FaTrashCan,
  FaArrowTrendDown,
  FaArrowTrendUp,
  FaTruck,
  FaUpload,
  FaUser,
  FaUserCheck,
  FaUserGear,
  FaUserPlus,
  FaUsers,
  FaWallet,
  FaWarehouse,
  FaWifi,
  FaWrench,
  FaXmark,
  FaCircleXmark,
} from 'react-icons/fa6';

// Define LucideIcon type for compatibility
export type LucideIcon = React.ComponentType<any>;

// Export FontAwesome icons using Lucide names
export {
  FaHeartPulse as Activity,
  FaCircleExclamation as AlertCircle,
  FaTriangleExclamation as AlertTriangle,
  FaBoxArchive as Archive,
  FaCircleArrowDown as ArrowDownCircle,
  FaArrowDown as ArrowDownRight,
  FaArrowRight as ArrowRight,
  FaRightLeft as ArrowRightLeft,
  FaCircleArrowUp as ArrowUpCircle,
  FaArrowUp as ArrowUpRight,
  FaCircleCheck as BadgeCheck,
  FaChartBar as BarChart2,
  FaChartSimple as BarChart3,
  FaBell as Bell,
  FaBell as BellRing,
  FaBox as Box,
  FaBoxesStacked as Boxes,
  FaTrowelBricks as BrickWall,
  FaBuilding as Building2,
  FaCalculator as Calculator,
  FaCalendarDays as Calendar,
  FaCalendarCheck as CalendarCheck,
  FaCamera as Camera,
  FaCheck as Check,
  FaCircleCheck as CheckCircle,
  FaCircleCheck as CheckCircle2,
  FaChevronDown as ChevronDown,
  FaChevronLeft as ChevronLeft,
  FaChevronRight as ChevronRight,
  FaClipboard as Clipboard,
  FaClipboardCheck as ClipboardCheck,
  FaClock as Clock,
  FaCoins as Coins,
  FaCompass as Compass,
  FaMicrochip as Cpu,
  FaCreditCard as CreditCard,
  FaDollarSign as DollarSign,
  FaDownload as Download,
  FaPen as Edit,
  FaPenToSquare as Edit2,
  FaArrowUpRightFromSquare as ExternalLink,
  FaEye as Eye,
  FaIndustry as Factory,
  FaFileCircleCheck as FileCheck,
  FaClockRotateLeft as FileClock,
  FaFileCode as FileCode,
  FaFileArrowDown as FileDown,
  FaFileLines as FileSearch,
  FaFileExcel as FileSpreadsheet,
  FaFileLines as FileText,
  FaFilter as Filter,
  FaSeedling as Flower,
  FaFolderTree as FolderTree,
  FaGlobe as Globe,
  FaHandHoldingDollar as HandCoins,
  FaHandshake as Handshake,
  FaHardDrive as HardDrive,
  FaHelmetSafety as HardHat,
  FaCircleQuestion as HelpCircle,
  FaClockRotateLeft as History,
  FaImage as Image,
  FaKey as Key,
  FaKey as KeyRound,
  FaLandmark as Landmark,
  FaLayerGroup as Layers,
  FaGauge as LayoutDashboard,
  FaBorderAll as LayoutGrid,
  FaSpinner as Loader2,
  FaLock as Lock,
  FaLock as LockKeyhole,
  FaRightFromBracket as LogOut,
  FaEnvelope as Mail,
  FaMapPin as MapPin,
  FaBox as Package,
  FaClipboardCheck as PackageCheck,
  FaPercent as Percent,
  FaPhone as Phone,
  FaChartPie as PieChart,
  FaPlay as Play,
  FaPlus as Plus,
  FaPrint as Printer,
  FaQrcode as QrCode,
  FaReceipt as Receipt,
  FaArrowsRotate as RefreshCw,
  FaRotateLeft as RotateCcw,
  FaFloppyDisk as Save,
  FaExpand as Scan,
  FaMagnifyingGlass as Search,
  FaPaperPlane as Send,
  FaGear as Settings,
  FaFileExcel as Sheet,
  FaShield as Shield,
  FaShieldHalved as ShieldAlert,
  FaShieldHalved as ShieldCheck,
  FaBagShopping as ShoppingBag,
  FaCartShopping as ShoppingCart,
  FaWandSparkles as Sparkles,
  FaTag as Tag,
  FaTrashCan as Trash2,
  FaArrowTrendDown as TrendingDown,
  FaArrowTrendUp as TrendingUp,
  FaTruck as Truck,
  FaUpload as Upload,
  FaUser as User,
  FaUserCheck as UserCheck,
  FaUserGear as UserCog,
  FaUserPlus as UserPlus,
  FaUsers as Users,
  FaWallet as WalletCards,
  FaWarehouse as Warehouse,
  FaWifi as WifiOff,
  FaWrench as Wrench,
  FaXmark as X,
  FaCircleXmark as XCircle,
};
