/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Customer,
  Supplier,
  Product,
  StockMovement,
  SalesOrder,
  Quotation,
  Invoice,
  Payment,
  PurchaseOrder,
  KubahProject,
} from './types';

export const initialCustomers: Customer[] = [
  {
    id: 'c1',
    code: 'CST-001',
    name: 'H. Ahmad Syukur',
    phone: '081234567890',
    city: 'Surabaya',
    address: 'Jl. Pemuda No. 12, Genteng',
    email: 'ahmad@gmail.com',
    status: 'Aktif',
  },
  {
    id: 'c2',
    code: 'CST-002',
    name: 'Yayasan Al-Ikhlas',
    phone: '085712345678',
    city: 'Sidoarjo',
    address: 'Perum Gading Fajar Blok C-4',
    email: 'alikhlas.sidoarjo@yahoo.com',
    status: 'Aktif',
  },
  {
    id: 'c3',
    code: 'CST-003',
    name: 'PT Maju Konstruksi Utama',
    phone: '082199887766',
    city: 'Gresik',
    address: 'Kawasan Industri Maspion Blok 5A',
    email: 'info@majukonstruksi.co.id',
    status: 'Aktif',
  },
  {
    id: 'c4',
    code: 'CST-004',
    name: 'Bapak Hermawan',
    phone: '081344556677',
    city: 'Malang',
    address: 'Jl. Ijen No. 44, Klojen',
    email: 'hermawan.m@outlook.com',
    status: 'Aktif',
  },
  {
    id: 'c5',
    code: 'CST-005',
    name: 'Takmir Masjid Baiturrahman',
    phone: '088877776666',
    city: 'Mojokerto',
    address: 'Dsn. Balong Krajan RT 02 RW 01',
    email: 'baiturrahman.mojokerto@gmail.com',
    status: 'Aktif',
  },
  {
    id: 'c6',
    code: 'CST-006',
    name: 'Ibu Listiawati',
    phone: '081288334411',
    city: 'Surabaya',
    address: 'Perum Citraland Cluster Oakwood B5',
    email: 'listiawati.res@gmail.com',
    status: 'Nonaktif',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 's1',
    code: 'SPL-001',
    name: 'PT Semen Indonesia Group',
    contactName: 'Budi Santoso',
    phone: '021-390888',
    city: 'Tuban',
    address: 'Kawasan Pabrik Semen Gresik, Tuban',
    status: 'Aktif',
  },
  {
    id: 's2',
    code: 'SPL-002',
    name: 'CV Baja Abadi Sejahtera',
    contactName: 'Hendriyanto',
    phone: '08112233445',
    city: 'Surabaya',
    address: 'Kawasan Industri Margomulyo No. 18',
    status: 'Aktif',
  },
  {
    id: 's3',
    code: 'SPL-003',
    name: 'Toko Cat & Pigmen Warna Cemerlang',
    contactName: 'Ibu Shanti',
    phone: '031-847291',
    city: 'Surabaya',
    address: 'Jl. Raya Darmo Indah No. 5',
    status: 'Aktif',
  },
  {
    id: 's4',
    code: 'SPL-004',
    name: 'UD Pasir Lumajang Super',
    contactName: 'Sholeh',
    phone: '085233669911',
    city: 'Lumajang',
    address: 'Dusun Kali Pasir No. 120',
    status: 'Aktif',
  },
  {
    id: 's5',
    code: 'SPL-005',
    name: 'Pembibitan Tanaman Agro Lestari',
    contactName: 'Wahyu',
    phone: '081922883344',
    city: 'Batu',
    address: 'Jl. Raya Oro-Oro Ombo No. 74',
    status: 'Aktif',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'p1',
    sku: 'KBH-GRC-D6',
    name: 'Kubah Masjid GRC Motif Madinah D-6m',
    category: 'Kubah Masjid',
    costPrice: 45000000,
    sellingPrice: 75000000,
    stock: 2,
    unit: 'Unit',
    location: 'Workshop Utama A',
    minStock: 1,
    status: 'Aman',
  },
  {
    id: 'p2',
    sku: 'KBH-ENM-D4',
    name: 'Kubah Masjid Enamel Platinum D-4m',
    category: 'Kubah Masjid',
    costPrice: 35000000,
    sellingPrice: 58000000,
    stock: 1,
    unit: 'Unit',
    location: 'Workshop Utama A',
    minStock: 1,
    status: 'Aman',
  },
  {
    id: 'p3',
    sku: 'LSP-BTN-C30',
    name: 'Lisplang Beton Klasik Lebar 30cm',
    category: 'Lisplang',
    costPrice: 45000,
    sellingPrice: 75000,
    stock: 250,
    unit: 'Meter',
    location: 'Gudang Beton B',
    minStock: 50,
    status: 'Aman',
  },
  {
    id: 'p4',
    sku: 'LSP-BTN-M20',
    name: 'Lisplang Beton Minimalis Lebar 20cm',
    category: 'Lisplang',
    costPrice: 32000,
    sellingPrice: 55000,
    stock: 45,
    unit: 'Meter',
    location: 'Gudang Beton B',
    minStock: 100,
    status: 'Menipis',
  },
  {
    id: 'p5',
    sku: 'RST-BTN-MIN',
    name: 'Roster Beton Minimalis Motif Kotak Silang',
    category: 'Roster',
    costPrice: 8500,
    sellingPrice: 15000,
    stock: 1200,
    unit: 'Pcs',
    location: 'Rak Roster Barat',
    minStock: 200,
    status: 'Aman',
  },
  {
    id: 'p6',
    sku: 'RST-BTN-DST',
    name: 'Roster Beton Terakota Estetik Oval',
    category: 'Roster',
    costPrice: 12000,
    sellingPrice: 22000,
    stock: 12,
    unit: 'Pcs',
    location: 'Rak Roster Barat',
    minStock: 150,
    status: 'Menipis',
  },
  {
    id: 'p7',
    sku: 'ORN-BTN-MHR',
    name: 'Ornamen Mihrab Kaligrafi Beton GRC',
    category: 'Ornamen Beton',
    costPrice: 8500000,
    sellingPrice: 14000000,
    stock: 3,
    unit: 'Set',
    location: 'Gudang Ornamen C',
    minStock: 2,
    status: 'Aman',
  },
  {
    id: 'p8',
    sku: 'ORN-BTN-PIL',
    name: 'Pilar Beton Korintian Cetak T-3m',
    category: 'Ornamen Beton',
    costPrice: 1800000,
    sellingPrice: 3200000,
    stock: 0,
    unit: 'Batang',
    location: 'Gudang Ornamen C',
    minStock: 5,
    status: 'Habis',
  },
  {
    id: 'p9',
    sku: 'PLN-PCK-MRH',
    name: 'Tanaman Hias Pucuk Merah Rimbun Tinggi 1m',
    category: 'Tanaman',
    costPrice: 35000,
    sellingPrice: 65000,
    stock: 85,
    unit: 'Pohon',
    location: 'Kavling Pembibitan D',
    minStock: 30,
    status: 'Aman',
  },
  {
    id: 'p10',
    sku: 'POT-BTN-MIN',
    name: 'Pot Minimalis Beton Cetak D-40',
    category: 'Tanaman',
    costPrice: 60000,
    sellingPrice: 110000,
    stock: 22,
    unit: 'Pcs',
    location: 'Kavling Pembibitan D',
    minStock: 15,
    status: 'Aman',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'm1',
    sku: 'LSP-BTN-C30',
    productName: 'Lisplang Beton Klasik Lebar 30cm',
    type: 'Masuk',
    quantity: 150,
    referenceDoc: 'PO-2026-05-012',
    date: '2026-05-28 09:15',
    handler: 'Gudang - Wahyu',
    notes: 'Hasil produksi cetak harian, kualitas grade A.',
  },
  {
    id: 'm2',
    sku: 'RST-BTN-MIN',
    productName: 'Roster Beton Minimalis Motif Kotak Silang',
    type: 'Keluar',
    quantity: 350,
    referenceDoc: 'SO-2026-05-088',
    date: '2026-05-28 14:30',
    handler: 'Gudang - Wahyu',
    notes: 'Pengiriman pesanan Yayasan Al-Ikhlas Sidoarjo.',
  },
  {
    id: 'm3',
    sku: 'KBH-GRC-D6',
    productName: 'Kubah Masjid GRC Motif Madinah D-6m',
    type: 'Masuk',
    quantity: 1,
    referenceDoc: 'PO-2026-05-001',
    date: '2026-05-29 11:00',
    handler: 'Admin Gudang',
    notes: 'Kubah GRC masjid Baiturrahman selesai precast workshop.',
  },
  {
    id: 'm4',
    sku: 'RST-BTN-DST',
    productName: 'Roster Beton Terakota Estetik Oval',
    type: 'Keluar',
    quantity: 120,
    referenceDoc: 'SO-2026-05-092',
    date: '2026-05-29 16:45',
    handler: 'Gudang - Wahyu',
    notes: 'Pembelian langsung Bapak Hermawan Malang untuk pagar hunian.',
  },
  {
    id: 'm5',
    sku: 'PLN-PCK-MRH',
    productName: 'Tanaman Hias Pucuk Merah Rimbun Tinggi 1m',
    type: 'Masuk',
    quantity: 50,
    referenceDoc: 'RCV-2026-05-031',
    date: '2026-05-30 08:30',
    handler: 'Admin Gudang',
    notes: 'Datang bibit baru dari supplier Batu.',
  },
];

export const initialQuotations: Quotation[] = [
  {
    id: 'q1',
    quoteNumber: 'Q-2026-05-004',
    customerName: 'Yayasan Al-Ikhlas',
    date: '2026-05-15',
    validUntil: '2026-06-15',
    total: 35000000,
    status: 'Disetujui',
    items: [
      { productName: 'Roster Beton Minimalis Motif Kotak Silang', quantity: 1500, price: 15000 },
      { productName: 'Lisplang Beton Klasik Lebar 30cm', quantity: 150, price: 75000 },
      { productName: 'Pot Minimalis Beton Cetak D-40', quantity: 10, price: 110000 },
    ],
  },
  {
    id: 'q2',
    quoteNumber: 'Q-2026-05-005',
    customerName: 'Takmir Masjid Baiturrahman',
    date: '2026-05-20',
    validUntil: '2026-06-20',
    total: 75000000,
    status: 'Terkirim',
    items: [
      { productName: 'Kubah Masjid GRC Motif Madinah D-6m', quantity: 1, price: 75000000 },
    ],
  },
  {
    id: 'q3',
    quoteNumber: 'Q-2026-05-006',
    customerName: 'PT Maju Konstruksi Utama',
    date: '2026-05-25',
    validUntil: '2026-06-25',
    total: 10400000,
    status: 'Draft',
    items: [
      { productName: 'Pilar Beton Korintian Cetak T-3m', quantity: 4, price: 3200000 },
    ],
  },
];

export const initialSalesOrders: SalesOrder[] = [
  {
    id: 'so1',
    orderNumber: 'SO-2026-05-088',
    customerName: 'Yayasan Al-Ikhlas',
    date: '2026-05-18',
    total: 35000000,
    status: 'Diproses',
    items: [
      { productName: 'Roster Beton Minimalis Motif Kotak Silang', quantity: 1500, price: 15000 },
      { productName: 'Lisplang Beton Klasik Lebar 30cm', quantity: 150, price: 75000 },
      { productName: 'Pot Minimalis Beton Cetak D-40', quantity: 10, price: 110000 },
    ],
  },
  {
    id: 'so2',
    orderNumber: 'SO-2026-05-089',
    customerName: 'Bapak Hermawan',
    date: '2026-05-22',
    total: 5120000,
    status: 'Selesai',
    items: [
      { productName: 'Roster Beton Terakota Estetik Oval', quantity: 120, price: 22000 },
      { productName: 'Tanaman Hias Pucuk Merah Rimbun Tinggi 1m', quantity: 20, price: 65000 },
      { productName: 'Pot Minimalis Beton Cetak D-40', quantity: 10, price: 110000 },
    ],
  },
  {
    id: 'so3',
    orderNumber: 'SO-2026-05-090',
    customerName: 'H. Ahmad Syukur',
    date: '2026-05-24',
    total: 114000000,
    status: 'Draft',
    items: [
      { productName: 'Kubah Masjid GRC Motif Madinah D-6m', quantity: 1, price: 75000000 },
      { productName: 'Kubah Masjid Enamel Platinum D-4m', quantity: 1, price: 58000000 },
    ],
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv1',
    invoiceNumber: 'INV-2026-05-104',
    customerName: 'Yayasan Al-Ikhlas',
    date: '2026-05-18',
    dueDate: '2026-06-18',
    total: 35000000,
    paidAmount: 15000000,
    status: 'Sebagian Dibayar',
  },
  {
    id: 'inv2',
    invoiceNumber: 'INV-2026-05-105',
    customerName: 'Bapak Hermawan',
    date: '2026-05-22',
    dueDate: '2026-06-05',
    total: 5120000,
    paidAmount: 5120000,
    status: 'Lunas',
  },
  {
    id: 'inv3',
    invoiceNumber: 'INV-2026-05-106',
    customerName: 'H. Ahmad Syukur',
    date: '2026-04-10',
    dueDate: '2026-05-10',
    total: 25000000,
    paidAmount: 0,
    status: 'Overdue',
  },
  {
    id: 'inv4',
    invoiceNumber: 'INV-2026-05-107',
    customerName: 'Takmir Masjid Baiturrahman',
    date: '2026-05-25',
    dueDate: '2026-06-25',
    total: 75000000,
    paidAmount: 0,
    status: 'Belum Lunas',
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay1',
    paymentNumber: 'PAY-2026-05-045',
    invoiceNumber: 'INV-2026-05-105',
    customerName: 'Bapak Hermawan',
    date: '2026-05-22 10:30',
    method: 'QRIS',
    amount: 5120000,
    status: 'Verified',
  },
  {
    id: 'pay2',
    paymentNumber: 'PAY-2026-05-046',
    invoiceNumber: 'INV-2026-05-104',
    customerName: 'Yayasan Al-Ikhlas',
    date: '2026-05-18 15:45',
    method: 'Transfer',
    amount: 15000000,
    status: 'Verified',
  },
  {
    id: 'pay3',
    paymentNumber: 'PAY-2026-05-047',
    invoiceNumber: 'INV-2026-05-106',
    customerName: 'H. Ahmad Syukur',
    date: '2026-05-29 13:00',
    method: 'Transfer',
    amount: 10000000,
    status: 'Pending',
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po1',
    poNumber: 'PO-2026-05-011',
    supplierName: 'PT Semen Indonesia Group',
    date: '2026-05-10',
    total: 18500000,
    status: 'Diterima Penuh',
    items: [
      { productName: 'Semen Portland OPC 50Kg', quantity: 200, price: 65000 },
      { productName: 'Mortar Beton Instan', quantity: 100, price: 55000 },
    ],
  },
  {
    id: 'po2',
    poNumber: 'PO-2026-05-012',
    supplierName: 'CV Baja Abadi Sejahtera',
    date: '2026-05-22',
    total: 24000000,
    status: 'Diterima Sebagian',
    items: [
      { productName: 'Besi Wiremesh M8', quantity: 50, price: 380000 },
      { productName: 'Besi Beton Ulir 12mm', quantity: 100, price: 50000 },
    ],
  },
  {
    id: 'po3',
    poNumber: 'PO-2026-05-013',
    supplierName: 'UD Pasir Lumajang Super',
    date: '2026-05-28',
    total: 6200000,
    status: 'Dipesan',
    items: [
      { productName: 'Pasir Lumajang - Truk Colt Diesel', quantity: 4, price: 1550000 },
    ],
  },
];

export const initialKubahProjects: KubahProject[] = [
  {
    id: 'proj1',
    code: 'PRJ-KBH-001',
    customerName: 'Takmir Masjid Baiturrahman',
    mosqueName: 'Masjid Jami Baiturrahman',
    location: 'Mojokerto, Jawa Timur',
    domeDiameter: 'D 6 Meter (Tinggi 4.5 Meter)',
    contractValue: 75000000,
    deadline: '2026-08-15',
    progress: 45,
    status: 'Produksi',
    timeline: [
      {
        date: '2026-05-05',
        stage: 'Survey Lokasi',
        description: 'Pengukuran dudukan kubah dialpangan (ring beam) selesai dilakukan oleh tim survey.',
        icon: 'Compass',
      },
      {
        date: '2026-05-12',
        stage: 'Penawaran Harga',
        description: 'Quotation Q-2026-05-005 dikirimkan dan disepakati oleh Panitia Pembangunan.',
        icon: 'FileText',
      },
      {
        date: '2026-05-18',
        stage: 'Deal Kontrak & DP',
        description: 'Penandatanganan Mou Kerja Sama. Pembayaran termin ke-1 (DP 30%) berhasil divalidasi.',
        icon: 'Handshake',
      },
      {
        date: '2026-05-24',
        stage: 'Produksi Precast GRC',
        description: 'Pembuatan cetakan kubah motif Madinah. Pengelasan rangka baja primer di workshop CV Beton Agung.',
        icon: 'Cpu',
      },
    ],
    termin: [
      { phase: 'Termin 1 (DP 30% - Desain & Rangka Baja)', amount: 22500000, dueDate: '2026-05-18', status: 'Lunas' },
      { phase: 'Termin 2 (Production Progress GRC 50%)', amount: 22500000, dueDate: '2026-06-25', status: 'Belum Bayar' },
      { phase: 'Termin 3 (Pelunasan - Kubah Finish / Serah Terima)', amount: 30000000, dueDate: '2026-08-15', status: 'Belum Bayar' },
    ],
    documentation: [
      {
        id: 'doc1',
        title: 'Hasil Survey Ring Beam Masjid',
        imageUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&q=80&w=400',
        date: '2026-05-05',
      },
      {
        id: 'doc2',
        title: 'Fabrikasi Rangka Pendukung Utama',
        imageUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=400',
        date: '2026-05-26',
      },
    ],
  },
  {
    id: 'proj2',
    code: 'PRJ-KBH-002',
    customerName: 'Yayasan Al-Ikhlas',
    mosqueName: 'Masjid Al-Muthmainnah',
    location: 'Sidoarjo, Jawa Timur',
    domeDiameter: 'D 8 Meter (Tinggi 6 Meter)',
    contractValue: 125000000,
    deadline: '2026-07-10',
    progress: 85,
    status: 'Pemasangan',
    timeline: [
      {
        date: '2026-04-01',
        stage: 'Survey',
        description: 'Survey kelayakan dan kekuatan struktur beton penopang kubah.',
        icon: 'Compass',
      },
      {
        date: '2026-04-10',
        stage: 'Deal',
        description: 'DP 40% dibayar dan SPK ditandatangani.',
        icon: 'Handshake',
      },
      {
        date: '2026-05-02',
        stage: 'Produksi Selesai',
        description: 'Segmen-segmen ornamen kubah GRC selesai dicor dan dikeringkan di workshop.',
        icon: 'Cpu',
      },
      {
        date: '2026-05-15',
        stage: 'Pengiriman',
        description: 'Material kubah diberangkatkan menggunakan armada truk tronton CV Beton Agung.',
        icon: 'Truck',
      },
      {
        date: '2026-05-20',
        stage: 'Pemasangan Scaffold & Panel GRC',
        description: 'Proses pemasangan rangka kubah di atap masjid Sidoarjo.',
        icon: 'Wrench',
      },
    ],
    termin: [
      { phase: 'Termin 1 (DP 40%)', amount: 50000000, dueDate: '2026-04-10', status: 'Lunas' },
      { phase: 'Termin 2 (Progress Produksi Selesai 30%)', amount: 37500000, dueDate: '2026-05-02', status: 'Lunas' },
      { phase: 'Termin 3 (Pelunasan Setelah Pemasangan Selesai)', amount: 37500000, dueDate: '2026-07-10', status: 'Belum Bayar' },
    ],
    documentation: [
      {
        id: 'doc3',
        title: 'Pengiriman GRC Panel ke Lokasi',
        imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=400',
        date: '2026-05-15',
      },
      {
        id: 'doc4',
        title: 'Ereksi Rangka GRC Masjid Sidoarjo',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=400',
        date: '2026-05-22',
      },
    ],
  },
  {
    id: 'proj3',
    code: 'PRJ-KBH-003',
    customerName: 'H. Ahmad Syukur',
    mosqueName: 'Musholla Ar-Rayyan',
    location: 'Surabaya, Jawa Timur',
    domeDiameter: 'D 3 Meter (Kubah Stainless Enamel)',
    contractValue: 45000000,
    deadline: '2026-09-30',
    progress: 15,
    status: 'Penawaran',
    timeline: [
      {
        date: '2026-05-20',
        stage: 'Survey Lokasi',
        description: 'Pengukuran atap ruko yang akan didirikan kubah musholla.',
        icon: 'Compass',
      },
      {
        date: '2026-05-28',
        stage: 'Pengiriman Penawaran',
        description: 'Penawaran harga kubah enamel stainless D3 terkirim ke Bapak H. Ahmad Syukur.',
        icon: 'FileText',
      },
    ],
    termin: [
      { phase: 'Down Payment 50%', amount: 22500000, dueDate: '2026-06-10', status: 'Belum Bayar' },
      { phase: 'Pelunasan COD Pemasangan', amount: 22500000, dueDate: '2026-09-30', status: 'Belum Bayar' },
    ],
    documentation: [],
  },
];
